server:
  port: ${HTTP_PORT:8080}

spring:
  application.name: VQueue
  rsocket.server:
    port: ${RSOCKET_SERVER_PORT:7000}
  jackson:
    default-property-inclusion: non_null
    mapper.sort-properties-alphabetically: true
  rabbitmq:
    host: ${AMQP_SERVER:localhost}
    port: ${AMQP_PORT:5672}
    ssl.enabled: false
    username: ${AMQP_USERNAME:admin}
    password: ${AMQP_PASSWORD:admin}
    virtual-host: /
    listener:
      simple:
        default-requeue-rejected: false

vqueue:
  amqp:
    eventExchangeName: event-exchange
    eventQueueName: event-queues

  couchbase:
    connectionString: ${COUCHBASE_HOSTS:localhost}
    bucketName: ${COUCHBASE_BUCKET:queue_bucket}
    userName: ${COUCHBASE_USERNAME:admin}
    password: ${COUCHBASE_PASSWORD:admin}